resources:  
  - name: helloworld 
    type: git  
    source:  
      uri: https://github.com/hossanrose/helloworld.git
      branch: master
jobs:  
  # Deploy the application to the AWS Beanstalk
  - name: Deploy
    plan:  
    - get: helloworld
      trigger: true
    - task: deploy-aws  
      params:
        AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: chriscamicas/awscli-awsebcli
        inputs:
            - name: helloworld
        run:
          path: sh
          args:
          - -c
          - |
            cd helloworld/app
            eb init continuous-deployment-demo -p "python-3.6" --region "us-west-2"
            eb create concourse-env --single
            eb deploy concourse-env
            eb status
